-- VER LAS COPIAS DE UN ARCHIVO
RESTORE HEADERONLY
FROM  DISK = N'G:\EGCC\BAK\RH_TOTAL.bak';
GO


RESTORE FILELISTONLY
FROM  DISK = N'G:\EGCC\BAK\RH_TOTAL.bak';
GO

RESTORE LABELONLY
FROM  DISK = N'G:\EGCC\BAK\RH_TOTAL.bak';
GO


RESTORE VERIFYONLY
FROM  DISK = N'G:\EGCC\BAK\RH_TOTAL.bak';
GO

