-- COPIA DE SEGURIDAD COMPLETA DE RH

BACKUP DATABASE [RH] 
TO  DISK = N'G:\EGCC\BAK\RH2.BAK' 
WITH FORMAT, INIT,  
	NAME = N'Copia de seguridad completa de RH', 
	SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

-- VER LAS COPIAS DE UN ARCHIVO
RESTORE HEADERONLY
FROM  DISK = N'G:\EGCC\BAK\RH2.BAK';
GO